# 2. Types of Binning

There are 3 major ways to create bins:

| Method     | Meaning                            | Good When…                                                     |
| ---------- | ---------------------------------- | -------------------------------------------------------------- |
| `pd.cut`   | Equal-width bins                   | You want fixed ranges                                          |
| `pd.qcut`  | Equal-frequency bins               | You want each bin to contain roughly the same number of people |
| `np.where` | Rule-based / domain knowledge bins | You want custom categories                                     |

# Binning with pd.cut() ----- (Equal-Width Bins)
PURPOSE:
Automatically divided data into bins of equal numeric width.
# Example:
Let's devide AGE into 4 equal sized bins.

In [1]:
import pandas as pd 
#sample data 
df = pd.DataFrame({ 'age' : [11,15,22,27,35,46,52,61,74,89]}) 
#create 4 equal-width bins
df['age_cut'] = pd.cut(df['age'], bins=4)
df

   age         age_cut
0   11  (10.922, 30.5]
1   15  (10.922, 30.5]
2   22  (10.922, 30.5]
3   27  (10.922, 30.5]
4   35    (30.5, 50.0]
5   46    (30.5, 50.0]
6   52    (50.0, 69.5]
7   61    (50.0, 69.5]
8   74    (69.5, 89.0]
9   89    (69.5, 89.0]

# Binning with pd.cut() + Labels
you can add meaningful labels.

In [2]:
bins = [10,20,30,50,70,100]
labels = [ 'teen', 'adult', 'young_mid', 'mid_age', 'senior']

df['age_group']=pd.cut(df['age'], bins=bins, labels=labels)

df

   age         age_cut  age_group
0   11  (10.922, 30.5]       teen
1   15  (10.922, 30.5]       teen
2   22  (10.922, 30.5]      adult
3   27  (10.922, 30.5]      adult
4   35    (30.5, 50.0]  young_mid
5   46    (30.5, 50.0]  young_mid
6   52    (50.0, 69.5]    mid_age
7   61    (50.0, 69.5]    mid_age
8   74    (69.5, 89.0]     senior
9   89    (69.5, 89.0]     senior

# Binning with pd.qcut() ----- (Equal- Frequency Bins)
Purpose:
Divides data so that each bin has almost the same number of observation.
if you have 1000 people and create 4 bins ---- each bin has ~250 people.
# Example:

In [3]:
df ['age_qcut'] = pd.qcut(df['age'],q=4)
df

   age         age_cut  age_group         age_qcut
0   11  (10.922, 30.5]       teen  (10.999, 23.25]
1   15  (10.922, 30.5]       teen  (10.999, 23.25]
2   22  (10.922, 30.5]      adult  (10.999, 23.25]
3   27  (10.922, 30.5]      adult    (23.25, 40.5]
4   35    (30.5, 50.0]  young_mid    (23.25, 40.5]
5   46    (30.5, 50.0]  young_mid    (40.5, 58.75]
6   52    (50.0, 69.5]    mid_age    (40.5, 58.75]
7   61    (50.0, 69.5]    mid_age    (58.75, 89.0]
8   74    (69.5, 89.0]     senior    (58.75, 89.0]
9   89    (69.5, 89.0]     senior    (58.75, 89.0]

# Binning with np.where() ----- ( Rule / Logic / Based )
why use it ........?
Teenager : Age < 20
Adult: 20---30
Middle: 30--60
Senior: Age ≥ 60

this connot always to be done with cut.

# Example:

In [ ]:
import numpy as np 
df ['age_custom'] = np.where()