In [1]:
import numpy as np

In [2]:
dir = np.__dir__()
print(dir)

['isdtype', 'nan', 'shares_memory', 'allclose', 'remainder', 'e', 'logspace', '__array_api_version__', '__version__', 'ScalarType', 'nextafter', 'isclose', 'trunc', 'array_repr', 'float64', 'transpose', '_specific_msg', 'char', 'expm1', 'show_runtime', 'float_power', 'triu_indices', 'degrees', 'logical_and', 'float32', '__getattr__', 'cumprod', 'nansum', 'intc', 'floor_divide', 'diff', 'rec', 'kaiser', 'sort_complex', 'mask_indices', 'int_', 'ufunc', 'correlate', 'shape', 'nancumprod', 'complex64', 'copysign', 'datetime_data', 'nanpercentile', 'tril', 'place', 'diag_indices', 'min', 'double', 'take', 'true_divide', 'uint8', 'datetime64', 'bitwise_invert', 'int32', 'partition', 'integer', 'ctypeslib', 'cdouble', 'nanargmin', 'number', '_pyinstaller_hooks_dir', 'byte', 'all', 'piecewise', 'kron', 'iscomplex', 'save', 'diagflat', 'can_cast', 'loadtxt', 'ravel_multi_index', 'argmin', 'common_type', 'ulong', 'arctan', 'little_endian', 'setbufsize', 'arcsin', 'convolve', 'intp', 'atan2', 'bitwise_right_shift', 'fromregex', 'busdaycalendar', 'identity', 'is_busday', 'reshape', 'ascontiguousarray', 'frombuffer', 'digitize', 'invert', 'isin', 'format_float_scientific', 'var', 'random', 'histogram', 'asmatrix', 'vectorize', 'amax', 'tril_indices', 'tile', 'frompyfunc', 'real_if_close', 'einsum_path', 'amin', 'bitwise_xor', 'clongdouble', 'True_', 'complexfloating', 'isnan', 'flipud', '_array_api_info', 'uint64', 'get_include', 'corrcoef', 'isreal', 'square', 'flatnonzero', 'bmat', 'fliplr', 'tanh', 'cosh', 'issubdtype', 'nanvar', 'uintc', 'conjugate', 'vecdot', '__loader__', 'tri', 'exp', 'array_equiv', 'nditer', 'concatenate', 'eye', 'histogramdd', 'array_split', 'vecmat', 'histogram2d', 'int64', 'array_equal', 'stack', '_int_extended_msg', 'greater_equal', '__former_attrs__', 'isfortran', 'hsplit', 'logical_or', 'compress', 'hanning', 'False_', 'ubyte', 'divmod', 'any', 'cumulative_sum', 'result_type', 'unique_all', 'extract', 'size', 'log1p', 'divide', 'require', 'bool', 'typename', 'fromiter', '__name__', 'binary_repr', 'timedelta64', 'histogram_bin_edges', 'arange', 'rot90', 'savetxt', 'equal', 'roll', 'hypot', 'unique_values', 'geomspace', 'printoptions', 'zeros', 'generic', 'index_exp', 'broadcast', 'ndim', 'deg2rad', 'arccos', 'str_', 'meshgrid', 'cross', 'nanmin', 'argmax', 'full_like', 'astype', 'real', 'trim_zeros', 'ediff1d', 'dsplit', 'less_equal', '_msg', 'dtype', '__file__', 'row_stack', 'nancumsum', 'isscalar', '_NoValue', 'typing', 'frexp', 'unique', 'fmod', 'broadcast_shapes', 'maximum', 'std', 'recarray', 'ceil', 'polyfit', 'memmap', 'fromstring', 'nan_to_num', 'inner', 'modf', 'log2', 'log10', 'inf', 'ravel', 'bitwise_or', 'rint', 'split', 'expand_dims', 'matrix', 'int8', 'indices', 'power', 'sign', 'floating', '__spec__', 'trace', 'unstack', 'put_along_axis', 'single', 'finfo', 'newaxis', 'less', 'tan', 'hstack', 'atleast_1d', '_core', 'geterrcall', 'apply_along_axis', 'int16', '__expired_attributes__', 'atleast_3d', 'mgrid', 'poly', 'repeat', 'ogrid', 'promote_types', 'put', 'minimum', 'ndindex', 'geterr', 'angle', 'cumulative_prod', 'broadcast_arrays', 'array_str', 'object_', 'percentile', 'r_', 'linspace', 'roots', '_typing', 'savez', 'insert', 'gcd', 'moveaxis', 'asin', 'bytes_', 'isneginf', 'triu_indices_from', 'isnat', 'acosh', 'fix', 'float16', '__NUMPY_SETUP__', 'lexsort', 'pi', 'nanmean', 'packbits', 'where', 'sinh', 'argpartition', 'rollaxis', 'typecodes', 'vdot', 'bartlett', 'min_scalar_type', 'broadcast_to', 'empty', 'flexible', 'ma', 'csingle', 'longlong', 'radians', 'ushort', 'pad', 'blackman', '__future_scalars__', 'character', 'seterrcall', 'flatiter', 'ndarray', 'conj', 'sqrt', 'test', 'inexact', 'einsum', '_utils', 'ix_', 'signbit', 'f2py', 'matmul', 'strings', 'ndenumerate', 'uintp', 'polymul', 'clip', '__array_namespace_info__', '_distributor_init', 'ldexp', 'tensordot', 'ones_like', 'concat', 'unique_inverse', 'long', 'nonzero', 'bitwise_count', 'get_printoptions', 'ptp', 'heaviside', 'argwhere', 'ulonglong', 'emath', 'hamming', 'apply_over_axes', 'asfortranarray', 'union1d', 'nested_iters', 'record', 'logaddexp2', 'atanh', 'isfinite', 'logaddexp', 'exp2', 'nanquantile', 'dot', 'imag', 'outer', 'fromfunction', 'short', 's_', 'asanyarray', '__config__', 'log', '__cached__', 'gradient', 'right_shift', 'median', 'unravel_index', 'left_shift', 'void', 'atleast_2d', 'errstate', '__dir__', 'polyval', '_expired_attrs_2_0', '__path__', 'negative', 'permute_dims', 'cbrt', 'genfromtxt', 'fmin', 'unpackbits', 'choose', 'acos', 'polyint', 'seterr', 'prod', 'bitwise_left_shift', 'mean', 'getbufsize', 'lib', 'i0', 'tril_indices_from', 'cos', 'empty_like', 'trapz', 'arctan2', 'iinfo', 'bincount', 'info', 'from_dlpack', 'rad2deg', 'fft', 'polynomial', 'spacing', 'poly1d', 'nanargmax', 'polydiv', 'unwrap', 'sinc', 'arcsinh', 'bitwise_not', 'iscomplexobj', '_type_info', 'round', 'set_printoptions', 'searchsorted', 'uint', 'full', 'multiply', '_CopyMode', 'isposinf', 'greater', '_mat', 'dstack', 'base_repr', 'asarray_chkfinite', 'cumsum', 'vsplit', 'diag', 'lcm', 'may_share_memory', 'flip', 'copy', 'matrix_transpose', 'asinh', 'swapaxes', 'uint32', 'dtypes', 'reciprocal', 'core', 'zeros_like', 'abs', '__numpy_submodules__', 'isinf', '__all__', 'arctanh', 'signedinteger', 'average', 'trapezoid', 'column_stack', 'arccosh', 'half', 'iterable', 'select', 'unsignedinteger', 'linalg', 'nanprod', 'vstack', 'mintypecode', 'argsort', '__builtins__', 'savez_compressed', 'sum', 'block', 'pow', 'uint16', 'exceptions', 'delete', 'bool_', 'unique_counts', 'fill_diagonal', 'testing', 'format_float_positional', 'polysub', 'asarray', 'atan', 'max', 'polyadd', 'datetime_as_string', 'positive', 'show_config', 'intersect1d', 'polyder', '__doc__', 'triu', 'fmax', '_globals', 'sin', 'sort', 'around', 'fabs', 'array', 'ones', 'add', 'complex128', 'vander', 'busday_count', 'c_', 'subtract', 'setxor1d', 'floor', 'isrealobj', 'euler_gamma', 'take_along_axis', 'array2string', 'logical_xor', 'diag_indices_from', 'squeeze', 'copyto', 'matvec', 'logical_not', 'bitwise_and', 'longdouble', 'fromfile', 'interp', 'count_nonzero', 'not_equal', 'nanmax', '__package__', 'resize', 'cov', 'diagonal', 'sctypeDict', 'setdiff1d', 'nanmedian', 'append', 'load', 'quantile', 'putmask', 'mod', 'absolute', 'in1d', 'busday_offset', 'nanstd', '_pytesttester']

In [3]:
import pandas as pd

In [4]:
dir = np.__dir__()
print(dir)

['isdtype', 'nan', 'shares_memory', 'allclose', 'remainder', 'e', 'logspace', '__array_api_version__', '__version__', 'ScalarType', 'nextafter', 'isclose', 'trunc', 'array_repr', 'float64', 'transpose', '_specific_msg', 'char', 'expm1', 'show_runtime', 'float_power', 'triu_indices', 'degrees', 'logical_and', 'float32', '__getattr__', 'cumprod', 'nansum', 'intc', 'floor_divide', 'diff', 'rec', 'kaiser', 'sort_complex', 'mask_indices', 'int_', 'ufunc', 'correlate', 'shape', 'nancumprod', 'complex64', 'copysign', 'datetime_data', 'nanpercentile', 'tril', 'place', 'diag_indices', 'min', 'double', 'take', 'true_divide', 'uint8', 'datetime64', 'bitwise_invert', 'int32', 'partition', 'integer', 'ctypeslib', 'cdouble', 'nanargmin', 'number', '_pyinstaller_hooks_dir', 'byte', 'all', 'piecewise', 'kron', 'iscomplex', 'save', 'diagflat', 'can_cast', 'loadtxt', 'ravel_multi_index', 'argmin', 'common_type', 'ulong', 'arctan', 'little_endian', 'setbufsize', 'arcsin', 'convolve', 'intp', 'atan2', 'bitwise_right_shift', 'fromregex', 'busdaycalendar', 'identity', 'is_busday', 'reshape', 'ascontiguousarray', 'frombuffer', 'digitize', 'invert', 'isin', 'format_float_scientific', 'var', 'random', 'histogram', 'asmatrix', 'vectorize', 'amax', 'tril_indices', 'tile', 'frompyfunc', 'real_if_close', 'einsum_path', 'amin', 'bitwise_xor', 'clongdouble', 'True_', 'complexfloating', 'isnan', 'flipud', '_array_api_info', 'uint64', 'get_include', 'corrcoef', 'isreal', 'square', 'flatnonzero', 'bmat', 'fliplr', 'tanh', 'cosh', 'issubdtype', 'nanvar', 'uintc', 'conjugate', 'vecdot', '__loader__', 'tri', 'exp', 'array_equiv', 'nditer', 'concatenate', 'eye', 'histogramdd', 'array_split', 'vecmat', 'histogram2d', 'int64', 'array_equal', 'stack', '_int_extended_msg', 'greater_equal', '__former_attrs__', 'isfortran', 'hsplit', 'logical_or', 'compress', 'hanning', 'False_', 'ubyte', 'divmod', 'any', 'cumulative_sum', 'result_type', 'unique_all', 'extract', 'size', 'log1p', 'divide', 'require', 'bool', 'typename', 'fromiter', '__name__', 'binary_repr', 'timedelta64', 'histogram_bin_edges', 'arange', 'rot90', 'savetxt', 'equal', 'roll', 'hypot', 'unique_values', 'geomspace', 'printoptions', 'zeros', 'generic', 'index_exp', 'broadcast', 'ndim', 'deg2rad', 'arccos', 'str_', 'meshgrid', 'cross', 'nanmin', 'argmax', 'full_like', 'astype', 'real', 'trim_zeros', 'ediff1d', 'dsplit', 'less_equal', '_msg', 'dtype', '__file__', 'row_stack', 'nancumsum', 'isscalar', '_NoValue', 'typing', 'frexp', 'unique', 'fmod', 'broadcast_shapes', 'maximum', 'std', 'recarray', 'ceil', 'polyfit', 'memmap', 'fromstring', 'nan_to_num', 'inner', 'modf', 'log2', 'log10', 'inf', 'ravel', 'bitwise_or', 'rint', 'split', 'expand_dims', 'matrix', 'int8', 'indices', 'power', 'sign', 'floating', '__spec__', 'trace', 'unstack', 'put_along_axis', 'single', 'finfo', 'newaxis', 'less', 'tan', 'hstack', 'atleast_1d', '_core', 'geterrcall', 'apply_along_axis', 'int16', '__expired_attributes__', 'atleast_3d', 'mgrid', 'poly', 'repeat', 'ogrid', 'promote_types', 'put', 'minimum', 'ndindex', 'geterr', 'angle', 'cumulative_prod', 'broadcast_arrays', 'array_str', 'object_', 'percentile', 'r_', 'linspace', 'roots', '_typing', 'savez', 'insert', 'gcd', 'moveaxis', 'asin', 'bytes_', 'isneginf', 'triu_indices_from', 'isnat', 'acosh', 'fix', 'float16', '__NUMPY_SETUP__', 'lexsort', 'pi', 'nanmean', 'packbits', 'where', 'sinh', 'argpartition', 'rollaxis', 'typecodes', 'vdot', 'bartlett', 'min_scalar_type', 'broadcast_to', 'empty', 'flexible', 'ma', 'csingle', 'longlong', 'radians', 'ushort', 'pad', 'blackman', '__future_scalars__', 'character', 'seterrcall', 'flatiter', 'ndarray', 'conj', 'sqrt', 'test', 'inexact', 'einsum', '_utils', 'ix_', 'signbit', 'f2py', 'matmul', 'strings', 'ndenumerate', 'uintp', 'polymul', 'clip', '__array_namespace_info__', '_distributor_init', 'ldexp', 'tensordot', 'ones_like', 'concat', 'unique_inverse', 'long', 'nonzero', 'bitwise_count', 'get_printoptions', 'ptp', 'heaviside', 'argwhere', 'ulonglong', 'emath', 'hamming', 'apply_over_axes', 'asfortranarray', 'union1d', 'nested_iters', 'record', 'logaddexp2', 'atanh', 'isfinite', 'logaddexp', 'exp2', 'nanquantile', 'dot', 'imag', 'outer', 'fromfunction', 'short', 's_', 'asanyarray', '__config__', 'log', '__cached__', 'gradient', 'right_shift', 'median', 'unravel_index', 'left_shift', 'void', 'atleast_2d', 'errstate', '__dir__', 'polyval', '_expired_attrs_2_0', '__path__', 'negative', 'permute_dims', 'cbrt', 'genfromtxt', 'fmin', 'unpackbits', 'choose', 'acos', 'polyint', 'seterr', 'prod', 'bitwise_left_shift', 'mean', 'getbufsize', 'lib', 'i0', 'tril_indices_from', 'cos', 'empty_like', 'trapz', 'arctan2', 'iinfo', 'bincount', 'info', 'from_dlpack', 'rad2deg', 'fft', 'polynomial', 'spacing', 'poly1d', 'nanargmax', 'polydiv', 'unwrap', 'sinc', 'arcsinh', 'bitwise_not', 'iscomplexobj', '_type_info', 'round', 'set_printoptions', 'searchsorted', 'uint', 'full', 'multiply', '_CopyMode', 'isposinf', 'greater', '_mat', 'dstack', 'base_repr', 'asarray_chkfinite', 'cumsum', 'vsplit', 'diag', 'lcm', 'may_share_memory', 'flip', 'copy', 'matrix_transpose', 'asinh', 'swapaxes', 'uint32', 'dtypes', 'reciprocal', 'core', 'zeros_like', 'abs', '__numpy_submodules__', 'isinf', '__all__', 'arctanh', 'signedinteger', 'average', 'trapezoid', 'column_stack', 'arccosh', 'half', 'iterable', 'select', 'unsignedinteger', 'linalg', 'nanprod', 'vstack', 'mintypecode', 'argsort', '__builtins__', 'savez_compressed', 'sum', 'block', 'pow', 'uint16', 'exceptions', 'delete', 'bool_', 'unique_counts', 'fill_diagonal', 'testing', 'format_float_positional', 'polysub', 'asarray', 'atan', 'max', 'polyadd', 'datetime_as_string', 'positive', 'show_config', 'intersect1d', 'polyder', '__doc__', 'triu', 'fmax', '_globals', 'sin', 'sort', 'around', 'fabs', 'array', 'ones', 'add', 'complex128', 'vander', 'busday_count', 'c_', 'subtract', 'setxor1d', 'floor', 'isrealobj', 'euler_gamma', 'take_along_axis', 'array2string', 'logical_xor', 'diag_indices_from', 'squeeze', 'copyto', 'matvec', 'logical_not', 'bitwise_and', 'longdouble', 'fromfile', 'interp', 'count_nonzero', 'not_equal', 'nanmax', '__package__', 'resize', 'cov', 'diagonal', 'sctypeDict', 'setdiff1d', 'nanmedian', 'append', 'load', 'quantile', 'putmask', 'mod', 'absolute', 'in1d', 'busday_offset', 'nanstd', '_pytesttester']

In [ ]:
a1=np.array([1,2,3,4,5,6,]) # default dtype is int64
a1.dtype
a2=np.array([1.0,2.0,3.0,4.0,5.0,6.0]) # default dtype is float64
a2.dtype
a3=np.array([1,2,3,4,5,6],dtype=np.float64) # specify dtype as float64
a3.dtype
a4=np.array([1,2,3,4,5,6],dtype=np.int32) # specify dtype as int32
a3.dtype # check dtype

dtype('float64')

In [1]:
import os
os.getcwd() # get current working directory

'c:\\Users\\Noor Saba\\Dropbox\\PC\\Desktop\\Data Science with Python'

In [7]:
import pandas as pd

file_path = r"c:\Users\Noor Saba\Dropbox\PC\Desktop\Data Science with Python\stores.csv"
df = pd.read_csv(file_path)

print(df.head())

  StoreCode         StoreName     StoreType Location  OperatingCost  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0
1    STR102      Apparel Zone       Apparel    Delhi           21.0
2    STR103       Super Bazar  Super Market    Delhi           22.8
3    STR104      Super Market  Super Market    Delhi           21.4
4    STR105     Central Store  Super Market    Delhi           18.7

   Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0         60       160.0              110            3.90       2.620
1         60       160.0              110            3.90       2.875
2         40       108.0               93            3.85       2.320
3         60       258.0              110            3.08       3.215
4         80       360.0              175            3.15       3.440

   ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment
0          16.46         0               1       4             4
1          17.02         0               1       4             4
2          18.61         1               1       4             1
3          19.44         1               0       3             1
4          17.02         0               0       3             2

In [9]:
import pandas as pd

stores = pd.read_csv(r"c:\Users\Noor Saba\Dropbox\PC\Desktop\Data Science with Python\stores.csv")
stores.head() # display first 5 rows of the dataframe

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2

In [10]:
stores.info() # get summary of dataframe including data types and non-null counts
stores.describe() # get statistical summary of numerical columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StoreCode        32 non-null     object
 1   StoreName        32 non-null     object
 2   StoreType        32 non-null     object
 3   Location         32 non-null     object
 4   OperatingCost    32 non-null     float64
 5   Staff_Cnt        32 non-null     int64
 6   TotalSales       32 non-null     float64
 7   Total_Customers  32 non-null     int64
 8   AcqCostPercust   29 non-null     float64
 9   BasketSize       32 non-null     float64
 10  ProfitPercust    32 non-null     float64
 11  OwnStore         32 non-null     int64
 12  OnlinePresence   32 non-null     int64
 13  Tenure           32 non-null     int64
 14  StoreSegment     32 non-null     int64
dtypes: float64(5), int64(6), object(4)
memory usage: 3.9+ KB

,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
count,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,20.090625,61.875000,230.721875,146.687500,3.651034,3.217250,17.848750,0.437500,0.406250,3.687500,2.625000
std,6.026948,17.859216,123.938694,68.562868,0.532664,0.978457,1.786943,0.504016,0.498991,0.737804,1.211504
min,10.400000,40.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.000000
25%,15.425000,40.000000,120.825000,96.500000,3.150000,2.581250,16.892500,0.000000,0.000000,3.000000,2.000000
50%,19.200000,60.000000,196.300000,123.000000,3.730000,3.325000,17.710000,0.000000,0.000000,4.000000,2.000000
75%,22.800000,80.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.000000
max,33.900000,80.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,4.000000

In [ ]:
stores.columns # get list of column names

Index(['StoreCode', 'StoreName', 'StoreType', 'Location', 'OperatingCost',
       'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment'],
      dtype='object')

In [ ]:
stores.index # get index range

RangeIndex(start=0, stop=32, step=1)

In [14]:
stores2 = stores[['OperatingCost', 'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment']] # Chaining of operation - Subsetting + sampling

In [15]:
stores2.loc[1:5, ['OperatingCost','TotalSales', 'Total_Customers']] # Targeting user defined indexes

   OperatingCost  TotalSales  Total_Customers
1           21.0       160.0              110
2           22.8       108.0               93
3           21.4       258.0              110
4           18.7       360.0              175
5           18.1       225.0              105

In [16]:
# select_dtypes

stores_num = stores.select_dtypes(['int', 'float'])
stores_obj = stores.select_dtypes('object')

In [17]:
stores_obj.head()

  StoreCode         StoreName     StoreType Location
0    STR101  Electronics Zone  Electronincs    Delhi
1    STR102      Apparel Zone       Apparel    Delhi
2    STR103       Super Bazar  Super Market    Delhi
3    STR104      Super Market  Super Market    Delhi
4    STR105     Central Store  Super Market    Delhi

In [ ]:
# Deriving calculated columns (creating new columns)

# Get the sales values after applying 5% of the discount on the products

#stores['Discounted Sales'] = stores.TotalSales - stores.TotalSales * 0.05 # Broadcasting + vectorization are allowed

In [ ]:
#Create a new column: Discounted Sales
#    - Apply a 5% discount (multiply by 0.95)

stores['Discounted Sales'] = stores['TotalSales'] * 0.95   # 5% discount applied
stores.head() # display first 5 rows of the dataframe

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0

In [19]:
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0

In [21]:
#Create a new column: Total Cost
#    Formula: OperatingCost + (Total_Customers * AcqCostPercust)

stores['TotalCost'] = (
    stores['OperatingCost'] 
    + stores['Total_Customers'] * stores['AcqCostPercust'] # Total customer acquisition cost
)

stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95

# Below 22 is a clean, easy-to-understand, fully commented version explaining .assign(), .insert(), and the concepts of *args and **kwargs in a practical, simple way.

In [22]:
# -------------------------------------------------------------
# Using .assign() to create multiple new columns at once
# -------------------------------------------------------------

# .assign() lets you define several new columns in a single call.
# Each argument inside assign() becomes a new column in the dataframe.
# Syntax: .assign(NewColumn = expression, AnotherColumn = value)

stores = stores.assign(
    
    # Creating TotalCost2: same formula as before
    TotalCost2 = stores['OperatingCost'] 
                 + stores['Total_Customers'] * stores['AcqCostPercust'],
    
    # Creating RandomInfo: a constant value for demonstration
    RandomInfo = 10
)

stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost,TotalCost2,RandomInfo
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00,450.00,10
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00,450.00,10
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85,380.85,10
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20,360.20,10
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95,569.95,10

# What the code does:23

stores.insert(1, 'TotalCost3', stores.OperatingCost + stores.Total_Customers * stores.AcqCostPercust)

# .insert() adds a new column at a specific position

# insert() is used when you want the column to appear at a certain index in the dataframe.

# It does not append at the end; it places the column exactly where you say.

In [23]:
stores.insert(1, 'TotalCost3', stores.OperatingCost + stores.Total_Customers * stores.AcqCostPercust) # in memory operation - expensive operation

In [24]:
stores.head()

,StoreCode,TotalCost3,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost,TotalCost2,RandomInfo
0,STR101,450.00,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00,450.00,10
1,STR102,450.00,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00,450.00,10
2,STR103,380.85,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85,380.85,10
3,STR104,360.20,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20,360.20,10
4,STR105,569.95,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95,569.95,10

In [25]:
# -------------------------------------------------------------
# Dropping multiple columns from the dataframe
# -------------------------------------------------------------

# .drop() removes columns or rows from a dataframe.
# columns = [...] → list of column names you want to remove
# inplace=True → updates the existing dataframe directly (no need to reassign)

stores.drop(
    columns=['TotalCost2', 'RandomInfo', 'TotalCost3'], 
    inplace=True
)

# Display the updated dataframe to confirm the columns were removed
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95

In [26]:
# -------------------------------------------------------------
# Filtering the dataframe to get specific rows
# -------------------------------------------------------------

# Goal: Fetch only the stores that are located in Chennai.
# We use a boolean condition: stores.Location == 'Chennai'
# This condition returns True for rows where the location is Chennai.

chennai_stores = stores[stores['Location'] == 'Chennai']

# Display the filtered result
chennai_stores

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.150,22.90,1,0,4,2,133.76,395.20
9,STR110,Apparel Zone,Apparel,Chennai,19.2,60,167.6,123,3.92,3.440,18.30,1,0,4,4,159.22,501.36
10,STR111,Super Bazar,Super Market,Chennai,17.8,60,167.6,123,3.92,3.440,18.90,1,0,4,4,159.22,499.96
11,STR112,Super Market,Super Market,Chennai,16.4,80,275.8,180,NaN,4.070,17.40,0,0,3,3,262.01,NaN
12,STR113,Central Store,Super Market,Chennai,17.3,80,275.8,180,NaN,3.730,17.60,0,0,3,3,262.01,NaN
13,STR114,Apparel Zone,Apparel,Chennai,15.2,80,275.8,180,NaN,3.780,18.00,0,0,3,3,262.01,NaN
14,STR115,Fashion Bazar,Apparel,Chennai,10.4,80,472.0,205,2.93,5.250,17.98,0,0,3,4,448.40,611.05
15,STR116,Digital Bazar,Electronincs,Chennai,10.4,80,460.0,215,3.00,5.424,17.82,0,0,3,4,437.00,655.40

In [27]:
# -------------------------------------------------------------
# Filtering the dataframe for multiple locations
# -------------------------------------------------------------

# Goal: Select stores that are located in either Chennai OR Delhi.
# We use the OR operator | to combine two conditions.
# Each condition checks the Location column for a specific city.

selected_stores = stores[
    (stores['Location'] == 'Chennai') |
    (stores['Location'] == 'Delhi')
]

# Display the filtered rows
selected_stores

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.000,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.000,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.600,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.100,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.000,569.95
5,STR106,Apparel Zone,Apparel,Delhi,18.1,60,225.0,105,2.76,3.460,20.22,1,0,3,1,213.750,307.90
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.570,15.84,0,0,3,4,342.000,800.75
7,STR108,Digital Bazar,Electronincs,Delhi,24.4,40,146.7,62,3.69,3.190,20.00,1,0,4,2,139.365,253.18
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.150,22.90,1,0,4,2,133.760,395.20
9,STR110,Apparel Zone,Apparel,Chennai,19.2,60,167.6,123,3.92,3.440,18.30,1,0,4,4,159.220,501.36
10,STR111,Super Bazar,Super Market,Chennai,17.8,60,167.6,123,3.92,3.440,18.90,1,0,4,4,159.220,499.96
11,STR112,Super Market,Super Market,Chennai,16.4,80,275.8,180,NaN,4.070,17.40,0,0,3,3,262.010,NaN
12,STR113,Central Store,Super Market,Chennai,17.3,80,275.8,180,NaN,3.730,17.60,0,0,3,3,262.010,NaN
13,STR114,Apparel Zone,Apparel,Chennai,15.2,80,275.8,180,NaN,3.780,18.00,0,0,3,3,262.010,NaN
14,STR115,Fashion Bazar,Apparel,Chennai,10.4,80,472.0,205,2.93,5.250,17.98,0,0,3,4,448.400,611.05
15,STR116,Digital Bazar,Electronincs,Chennai,10.4,80,460.0,215,3.00,5.424,17.82,0,0,3,4,437.000,655.40

In [28]:
# Select only the stores located in Chennai or Delhi
filtered_stores = stores[stores['Location'].isin(['Chennai', 'Delhi'])]

# Display the result
print(filtered_stores)

   StoreCode         StoreName     StoreType Location  OperatingCost  \
0     STR101  Electronics Zone  Electronincs    Delhi           21.0
1     STR102      Apparel Zone       Apparel    Delhi           21.0
2     STR103       Super Bazar  Super Market    Delhi           22.8
3     STR104      Super Market  Super Market    Delhi           21.4
4     STR105     Central Store  Super Market    Delhi           18.7
5     STR106      Apparel Zone       Apparel    Delhi           18.1
6     STR107     Fashion Bazar       Apparel    Delhi           14.3
7     STR108     Digital Bazar  Electronincs    Delhi           24.4
8     STR109  Electronics Zone  Electronincs  Chennai           22.8
9     STR110      Apparel Zone       Apparel  Chennai           19.2
10    STR111       Super Bazar  Super Market  Chennai           17.8
11    STR112      Super Market  Super Market  Chennai           16.4
12    STR113     Central Store  Super Market  Chennai           17.3
13    STR114      Apparel Zone       Apparel  Chennai           15.2
14    STR115     Fashion Bazar       Apparel  Chennai           10.4
15    STR116     Digital Bazar  Electronincs  Chennai           10.4

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
0          60       160.0              110            3.90       2.620
1          60       160.0              110            3.90       2.875
2          40       108.0               93            3.85       2.320
3          60       258.0              110            3.08       3.215
4          80       360.0              175            3.15       3.440
5          60       225.0              105            2.76       3.460
6          80       360.0              245            3.21       3.570
7          40       146.7               62            3.69       3.190
8          40       140.8               95            3.92       3.150
9          60       167.6              123            3.92       3.440
10         60       167.6              123            3.92       3.440
11         80       275.8              180             NaN       4.070
12         80       275.8              180             NaN       3.730
13         80       275.8              180             NaN       3.780
14         80       472.0              205            2.93       5.250
15         80       460.0              215            3.00       5.424

    ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment  \
0           16.46         0               1       4             4
1           17.02         0               1       4             4
2           18.61         1               1       4             1
3           19.44         1               0       3             1
4           17.02         0               0       3             2
5           20.22         1               0       3             1
6           15.84         0               0       3             4
7           20.00         1               0       4             2
8           22.90         1               0       4             2
9           18.30         1               0       4             4
10          18.90         1               0       4             4
11          17.40         0               0       3             3
12          17.60         0               0       3             3
13          18.00         0               0       3             3
14          17.98         0               0       3             4
15          17.82         0               0       3             4

    Discounted Sales  TotalCost
0            152.000     450.00
1            152.000     450.00
2            102.600     380.85
3            245.100     360.20
4            342.000     569.95
5            213.750     307.90
6            342.000     800.75
7            139.365     253.18
8            133.760     395.20
9            159.220     501.36
10           159.220     499.96
11           262.010        NaN
12           262.010        NaN
13           262.010        NaN
14           448.400     611.05
15           437.000     655.40

# Step-by-step explanation:28

stores['Location'] → looks at the Location column in your DataFrame.

.isin(['Chennai', 'Delhi']) → checks each row to see if the location is either 'Chennai' or 'Delhi'.

stores[...] → keeps only the rows where the condition is True.

filtered_stores → now contains only the stores in Chennai or Delhi.

In [29]:
# Get TotalSales and Total_Customers for stores in Chennai or Delhi
filtered_data = stores.loc[
    stores['Location'].isin(['Chennai', 'Delhi']),  # Keep rows where Location is Chennai or Delhi
    ['TotalSales', 'Total_Customers']              # Select only these two columns
]

print(filtered_data)

    TotalSales  Total_Customers
0        160.0              110
1        160.0              110
2        108.0               93
3        258.0              110
4        360.0              175
5        225.0              105
6        360.0              245
7        146.7               62
8        140.8               95
9        167.6              123
10       167.6              123
11       275.8              180
12       275.8              180
13       275.8              180
14       472.0              205
15       460.0              215

# Explanation in simple terms:29 

"Location in ['Chennai', 'Delhi']" is like saying: “Give me rows where Location is Chennai or Delhi”.

[['TotalSales', 'Total_Customers']] then picks only the columns you want.

Everything is compact and very readable, especially when dealing with multiple conditions.

This approach is great when you want the code to be almost like a natural-language filter.

In [30]:
# Find stores where TotalCost is higher than the average TotalCost

# Step 1: Calculate the average TotalCost
average_total_cost = stores['TotalCost'].mean()

# Step 2: Filter stores with TotalCost greater than average
high_cost_stores = stores[stores['TotalCost'] > average_total_cost]

# Step 3: Display the result
print(high_cost_stores)

   StoreCode         StoreName     StoreType Location  OperatingCost  \
4     STR105     Central Store  Super Market    Delhi           18.7
6     STR107     Fashion Bazar       Apparel    Delhi           14.3
14    STR115     Fashion Bazar       Apparel  Chennai           10.4
15    STR116     Digital Bazar  Electronincs  Chennai           10.4
16    STR117  Electronics Zone  Electronincs   Mumbai           14.7
23    STR124     Digital Bazar  Electronincs   Mumbai           13.3
24    STR125  Electronics Zone  Electronincs  Kolkata           19.2
28    STR129     Central Store  Super Market  Kolkata           15.8
29    STR130      Apparel Zone       Apparel  Kolkata           19.7
30    STR131     Fashion Bazar       Apparel  Kolkata           15.0

    Staff_Cnt  TotalSales  Total_Customers  AcqCostPercust  BasketSize  \
4          80       360.0              175            3.15       3.440
6          80       360.0              245            3.21       3.570
14         80       472.0              205            2.93       5.250
15         80       460.0              215            3.00       5.424
16         80       440.0              230            3.23       5.345
23         80       350.0              245            3.73       3.840
24         80       400.0              175            3.08       3.845
28         80       351.0              264            4.22       3.170
29         60       145.0              175            3.62       2.770
30         80       301.0              335            3.54       3.570

    ProfitPercust  OwnStore  OnlinePresence  Tenure  StoreSegment  \
4           17.02         0               0       3             2
6           15.84         0               0       3             4
14          17.98         0               0       3             4
15          17.82         0               0       3             4
16          17.42         0               0       3             4
23          15.41         0               0       3             4
24          17.05         0               0       3             2
28          14.50         0               1       5             4
29          15.50         0               1       5             4
30          14.60         0               1       5             4

    Discounted Sales  TotalCost
4             342.00     569.95
6             342.00     800.75
14            448.40     611.05
15            437.00     655.40
16            418.00     757.60
23            332.50     927.15
24            380.00     558.20
28            333.45    1129.88
29            137.75     653.20
30            285.95    1200.90

# Explanation in simple terms:30

stores['TotalCost'].mean() → calculates the average total cost across all stores.

stores['TotalCost'] > average_total_cost → creates a Boolean mask for stores above the average.

stores[...] → selects only the rows where the condition is True.

high_cost_stores → contains only stores with higher-than-average total cost.

This version is easier to read because it separates calculation from filtering, making it clear what each step does.

In [31]:
stores.TotalCost.mean() # calculate mean of TotalCost column

np.float64(527.8786206896551)

# 32..................
# Count the total Super Market stores in Delhi

# Think of it as a filter-and-count problem:

Step 1: Only focus on stores located in Delhi.

Step 2: From these Delhi stores, pick only those that are “Super Market.”

Step 3: Count how many are left.

In [34]:
# Step 1: Filter stores in Delhi using the 'Location' column
delhi_stores = stores[stores['Location'] == 'Delhi']

# Step 2: Count the total number of Super Market stores in Delhi
total_supermarkets_in_delhi = delhi_stores[delhi_stores['StoreType'] == 'Super Market'].shape[0]
print("Total Super Market stores in Delhi:", total_supermarkets_in_delhi)

# Step 3: Calculate total sales in Delhi
total_sales_in_delhi = delhi_stores['TotalSales'].sum()
print("Total sales in Delhi:", total_sales_in_delhi)

# Step 4: Rename columns for clarity
stores.rename(columns={
    'Total_Customers': 'TotalCustomers',
    'Staff_Cnt': 'StaffCnt'
}, inplace=True)

# Step 5: Preview the first few rows
print(stores.head())

Total Super Market stores in Delhi: 3
Total sales in Delhi: 1777.7
  StoreCode         StoreName     StoreType Location  OperatingCost  StaffCnt  \
0    STR101  Electronics Zone  Electronincs    Delhi           21.0        60
1    STR102      Apparel Zone       Apparel    Delhi           21.0        60
2    STR103       Super Bazar  Super Market    Delhi           22.8        40
3    STR104      Super Market  Super Market    Delhi           21.4        60
4    STR105     Central Store  Super Market    Delhi           18.7        80

   TotalSales  TotalCustomers  AcqCostPercust  BasketSize  ProfitPercust  \
0       160.0             110            3.90       2.620          16.46
1       160.0             110            3.90       2.875          17.02
2       108.0              93            3.85       2.320          18.61
3       258.0             110            3.08       3.215          19.44
4       360.0             175            3.15       3.440          17.02

   OwnStore  OnlinePresence  Tenure  StoreSegment  Discounted Sales  TotalCost
0         0               1       4             4             152.0     450.00
1         0               1       4             4             152.0     450.00
2         1               1       4             1             102.6     380.85
3         1               0       3             1             245.1     360.20
4         0               0       3             2             342.0     569.95

In [33]:
print(stores.columns)

Index(['StoreCode', 'StoreName', 'StoreType', 'Location', 'OperatingCost',
       'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment', 'Discounted Sales', 'TotalCost'],
      dtype='object')

In [35]:
#The original column in your DataFrame is called 
# 'Discounted Sales' (with a space).
# You are creating a new column called 'DiscountedSales' (no space).
# This is essentially duplicating the information, but the
#  new column name is easier to work with in code, because spaces
#  in column names can cause issues when referencing columns.



stores['DiscountedSales'] = stores['Discounted Sales']
 # information is repeated in another colunn

In [36]:
#This writes the current DataFrame (stores) to a CSV file named 'stores_new.csv'.
# index=False ensures the row numbers are not saved as a separate column in the CSV.
# After this, you have a clean CSV with the new column name 
# 'DiscountedSales', ready for analysis or sharing.



stores.to_csv('stores_new.csv', index=False)