# Data - 
    # Tabular data - structured data (rows & columns)
    # Semi structured data - JSON, xml (easily converted to tables with light processing of data)
    # Unstructed data - audio, video, images, etc.
# Pandas has 2 data structures:
# 1. Series - A column in a table
    # Properties:
        # a. 1D
        # b. Homogenous (single data type)
        # c. Broadcasting is allowed
        # d. Vectorization is allowed

# 2. dataframe - A complete table
    # Properties:
        # a. 2D
        # b. Hetrogenous (multiple data types)
        # c. Broadcasting is allowed
        # d. Vectorization is allowed

There are 2 different types of indexes:
1. Default index - defined by default in pandas data structures from 0 to n-1
2. User defined index - by default same as default index but can be manipulated by user (start to end).

.loc - targeting user defined index (preferred) [filtering of data]
.iloc - targeting default indexes

In data analysis, we will exercise following steps:
0. Data availability (data engineer)
1. Data Import
2. Understanding the data
    a. Metadata auditing (structure of data)
        -> Identifying the type of data
        -> # of rows
        -> # of columns
        -> Column names
        -> Type of table - long/wide/cross
    b. data auditing (what's in the data) - EDA (exploratory data analysis) - auditing + manipulation of the data 
        -> Identifying missings
        -> Identifying outliers
        -> Identifying duplicates
        -> Perform sorting
        -> Perform filtering
        -> Perform subsetting
        -> Aggregate
        -> Data Merge
            => JOINs [inner/left/right/outer]
            => Data Append [horizontal/vertical]
        -> Create Groups & Bins
        -> Charts/Visualizations

# Q. How to connect to a database in pandas? -> Postgres, SQL Server, MySQL

In [ ]:
import numpy as np
import pandas as pd # pandas - panel data analysis
# !pip install pandas

In [54]:
s1 = pd.Series([1,2,3,4,5], dtype = np.int32, name = 'int_nums')
s1.dtype

dtype('int32')

In [55]:
s1.shape

(5,)

In [56]:
s1.size

5

In [57]:
s1.ndim

1

In [58]:
s1.nbytes

20

In [59]:
s1

0    1
1    2
2    3
3    4
4    5
Name: int_nums, dtype: int32

In [60]:
s1[0]

np.int32(1)

In [78]:
s2 = pd.Series([6,7,8,9,10], dtype = np.int32, index = ['a','b','c','d','e']) # Indexes are hitting user defined index
s2

a     6
b     7
c     8
d     9
e    10
dtype: int32

In [79]:
s2['a':'d'] # Targeting user defined index

a    6
b    7
c    8
d    9
dtype: int32

In [80]:
s2[0:3] # Targeting default index

a    6
b    7
c    8
dtype: int32

In [81]:
s2['a']

np.int32(6)

In [82]:
# Add the numbers elements wise in s1 and s2

s1 + s2 # Vectorization

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [83]:
s2.reset_index(drop=True, inplace=True) # Drops the old index and defines default index

In [84]:
s1 + s2

0     7
1     9
2    11
3    13
4    15
dtype: int32

In [91]:
# Fetch only even values in s1 (filtering)
s1.loc[s1 % 2 == 0]

1    2
3    4
Name: int_nums, dtype: int32

In [92]:
s1.loc[s1 % 2 == 0]

1    2
3    4
Name: int_nums, dtype: int32

In [94]:
# sum, min, max, mean - numpy => pandas

a2 = np.arange(1,31).reshape((5,6))

In [97]:
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
a2.sum(axis=1) # Row wise sum

array([ 21,  57,  93, 129, 165])

In [ ]:
a2.sum(axis=0) # Col wise sum

array([65, 70, 75, 80, 85, 90])

In [103]:
d1 = {'Col1': [1,2,3], 'Col2': [2,3,4]}

dummy = pd.DataFrame(d1)

In [104]:
dummy

   Col1  Col2
0     1     2
1     2     3
2     3     4

In [117]:
dummy.loc[:,'Col1']

0    1
1    2
2    3
Name: Col1, dtype: int64

In [ ]:
df = pd.read_csv('stores.csv') # CSV/TSV are light weight substitutes of excel files.
df.head() # First 5 records

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2

In [ ]:
df.tail() # Last 5 records

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
27,STR128,Super Market,Super Market,Kolkata,30.4,40,95.1,113,3.77,1.513,16.9,1,1,5,2
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.170,14.5,0,1,5,4
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.770,15.5,0,1,5,4
30,STR131,Fashion Bazar,Apparel,Kolkata,15.0,80,301.0,335,3.54,3.570,14.6,0,1,5,4
31,STR132,Digital Bazar,Electronincs,Kolkata,21.4,40,121.0,109,4.11,2.780,18.6,1,1,4,2

In [125]:
df.head(10)

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2
5,STR106,Apparel Zone,Apparel,Delhi,18.1,60,225.0,105,2.76,3.460,20.22,1,0,3,1
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.570,15.84,0,0,3,4
7,STR108,Digital Bazar,Electronincs,Delhi,24.4,40,146.7,62,3.69,3.190,20.00,1,0,4,2
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.150,22.90,1,0,4,2
9,STR110,Apparel Zone,Apparel,Chennai,19.2,60,167.6,123,3.92,3.440,18.30,1,0,4,4

In [130]:
# Sampling the data
df.sample(5)

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.57,15.84,0,0,3,4
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.77,15.50,0,1,5,4
10,STR111,Super Bazar,Super Market,Chennai,17.8,60,167.6,123,3.92,3.44,18.90,1,0,4,4
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.15,22.90,1,0,4,2
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.17,14.50,0,1,5,4

In [131]:
df.ndim

2

In [132]:
df.shape

(32, 15)

In [133]:
df.dtypes

StoreCode           object
StoreName           object
StoreType           object
Location            object
OperatingCost      float64
Staff_Cnt            int64
TotalSales         float64
Total_Customers      int64
AcqCostPercust     float64
BasketSize         float64
ProfitPercust      float64
OwnStore             int64
OnlinePresence       int64
Tenure               int64
StoreSegment         int64
dtype: object

In [134]:
df.size

480

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StoreCode        32 non-null     object
 1   StoreName        32 non-null     object
 2   StoreType        32 non-null     object
 3   Location         32 non-null     object
 4   OperatingCost    32 non-null     float64
 5   Staff_Cnt        32 non-null     int64
 6   TotalSales       32 non-null     float64
 7   Total_Customers  32 non-null     int64
 8   AcqCostPercust   29 non-null     float64
 9   BasketSize       32 non-null     float64
 10  ProfitPercust    32 non-null     float64
 11  OwnStore         32 non-null     int64
 12  OnlinePresence   32 non-null     int64
 13  Tenure           32 non-null     int64
 14  StoreSegment     32 non-null     int64
dtypes: float64(5), int64(6), object(4)
memory usage: 3.9+ KB

In [ ]:
df.describe() # Descriptive stats

,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
count,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
mean,20.090625,61.875000,230.721875,146.687500,3.651034,3.217250,17.848750,0.437500,0.406250,3.687500,2.625000
std,6.026948,17.859216,123.938694,68.562868,0.532664,0.978457,1.786943,0.504016,0.498991,0.737804,1.211504
min,10.400000,40.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.000000
25%,15.425000,40.000000,120.825000,96.500000,3.150000,2.581250,16.892500,0.000000,0.000000,3.000000,2.000000
50%,19.200000,60.000000,196.300000,123.000000,3.730000,3.325000,17.710000,0.000000,0.000000,4.000000,2.000000
75%,22.800000,80.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.000000
max,33.900000,80.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,4.000000

In [138]:
df.describe(include = 'object')

       StoreCode     StoreName StoreType Location
count         32            32        32       32
unique        32             7         3        4
top       STR101  Apparel Zone   Apparel    Delhi
freq           1             8        12        8

In [139]:
df.describe(include='all')

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
count,32,32,32,32,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000
unique,32,7,3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,STR101,Apparel Zone,Apparel,Delhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,8,12,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,20.090625,61.875000,230.721875,146.687500,3.651034,3.217250,17.848750,0.437500,0.406250,3.687500,2.625000
std,NaN,NaN,NaN,NaN,6.026948,17.859216,123.938694,68.562868,0.532664,0.978457,1.786943,0.504016,0.498991,0.737804,1.211504
min,NaN,NaN,NaN,NaN,10.400000,40.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.000000
25%,NaN,NaN,NaN,NaN,15.425000,40.000000,120.825000,96.500000,3.150000,2.581250,16.892500,0.000000,0.000000,3.000000,2.000000
50%,NaN,NaN,NaN,NaN,19.200000,60.000000,196.300000,123.000000,3.730000,3.325000,17.710000,0.000000,0.000000,4.000000,2.000000
75%,NaN,NaN,NaN,NaN,22.800000,80.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.000000
max,NaN,NaN,NaN,NaN,33.900000,80.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,4.000000