In [1]:
# pd.cut vs pd.qcut vs np.where
import pandas as pd
import numpy as np

stores = pd.read_csv('stores_new.csv')
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,StaffCnt,TotalSales,TotalCustomers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95

In [20]:
# pd.cut
stores['sales_cat'] = pd.cut(stores.TotalSales, bins = 4, labels=['standard', 'silver', 'gold', 'premium']) # Equally spaced intervals on the given numbers.

In [21]:
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,StaffCnt,TotalSales,TotalCustomers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost,sales_cat
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00,standard
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00,standard
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85,standard
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20,silver
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95,gold

In [19]:
# pd.qcut

pd.qcut(stores.TotalSales, q = 4).value_counts(normalize=True) # All the 4 quantiles will have same data points (almost equal data points)

TotalSales
(71.09899999999999, 120.825]    0.25
(120.825, 196.3]                0.25
(196.3, 326.0]                  0.25
(326.0, 472.0]                  0.25
Name: proportion, dtype: float64

In [26]:
# Capture the high vs low footfall (2 equally spaced intervals) and fetch total sales by these 2 categories.

stores['footfall'] = pd.cut(stores.TotalCustomers, bins = 2, labels=['low', 'high'])

stores.loc[stores.footfall == 'low', 'TotalSales'].sum()

np.float64(4649.1)

In [27]:
stores.loc[stores.footfall == 'high', 'TotalSales'].sum()

np.float64(2734.0)

In [28]:
stores.footfall.value_counts()

footfall
low     25
high     7
Name: count, dtype: int64

In [ ]:
# np.where() => similar to IF function on google sheets/excel
# Capture the high vs low footfall (> 150) and fetch total sales by these 2 categories.
stores['footfall'] = np.where(stores.TotalCustomers > 150, 'High', 'Low')

In [36]:
stores.footfall.value_counts()

footfall
Low     19
High    13
Name: count, dtype: int64

In [38]:
stores.loc[stores.footfall == 'Low', 'TotalSales'].sum()

np.float64(2916.7)

In [39]:
stores.loc[stores.footfall == 'High', 'TotalSales'].sum()

np.float64(4466.4)

In [ ]:
# Aggregations - sum, min, max, average, count

# group by
# pivot table
# pivot
# crosstab

In [ ]:
# What is the Location wise Sales?

stores.groupby('Location').TotalSales.sum()

Location
Chennai    2235.4
Delhi      1777.7
Kolkata    1612.4
Mumbai     1757.6
Name: TotalSales, dtype: float64

In [46]:
# What's the total # of stores per store type?
stores.groupby('StoreType').StoreCode.count()

StoreType
Apparel         12
Electronincs     8
Super Market    12
Name: StoreCode, dtype: int64

In [47]:
# What's the Location wise footfall and sales

stores.groupby('Location')[['TotalSales', 'TotalCustomers']].sum()

          TotalSales  TotalCustomers
Location
Chennai       2235.4            1301
Delhi         1777.7            1010
Kolkata       1612.4            1328
Mumbai        1757.6            1055

In [ ]:
stores.groupby('Location').agg({'TotalSales': 'sum', 'TotalCustomers': 'sum'}) # sum as a function => sum as a string

          TotalSales  TotalCustomers
Location
Chennai       2235.4            1301
Delhi         1777.7            1010
Kolkata       1612.4            1328
Mumbai        1757.6            1055

In [51]:
# What's the Location wise average sales, total sales, min and max sales
stores.groupby('Location').TotalSales.agg(['sum', 'mean', 'min', 'max'])

             sum      mean    min    max
Location
Chennai   2235.4  279.4250  140.8  472.0
Delhi     1777.7  222.2125  108.0  360.0
Kolkata   1612.4  201.5500   79.0  400.0
Mumbai    1757.6  219.7000   71.1  440.0

In [52]:
stores.groupby('Location').agg({'TotalSales': ['sum', 'mean', 'min', 'max']})

         TotalSales
                sum      mean    min    max
Location
Chennai      2235.4  279.4250  140.8  472.0
Delhi        1777.7  222.2125  108.0  360.0
Kolkata      1612.4  201.5500   79.0  400.0
Mumbai       1757.6  219.7000   71.1  440.0

In [ ]:
# What's the total Sales by Location and Store Type

stores.groupby(['Location', 'StoreType']).TotalSales.sum().reset_index()

   Location     StoreType  TotalSales
0   Chennai       Apparel       915.4
1   Chennai  Electronincs       600.8
2   Chennai  Super Market       719.2
3     Delhi       Apparel       745.0
4     Delhi  Electronincs       306.7
5     Delhi  Super Market       726.0
6   Kolkata       Apparel       525.0
7   Kolkata  Electronincs       521.0
8   Kolkata  Super Market       566.4
9    Mumbai       Apparel       700.7
10   Mumbai  Electronincs       790.0
11   Mumbai  Super Market       266.9

In [62]:
stores.groupby(['Location', 'StoreType']).TotalSales.sum().reset_index().pivot(index = 'Location', columns = 'StoreType', values = 'TotalSales') #Cross table

StoreType  Apparel  Electronincs  Super Market
Location
Chennai      915.4         600.8         719.2
Delhi        745.0         306.7         726.0
Kolkata      525.0         521.0         566.4
Mumbai       700.7         790.0         266.9

In [ ]:
# Pivot tables -> Excel 
# Fetch Average total cost per store type and store name
# Hierarchical data
pd.pivot_table(data = stores, index = 'StoreName', columns='StoreType', values = 'TotalCost', aggfunc = 'mean', fill_value=0)

StoreType            Apparel  Electronincs  Super Market
StoreName
Apparel Zone      420.031429          0.00      0.000000
Central Store       0.000000          0.00    693.410000
Digital Bazar       0.000000        576.28      0.000000
Electronics Zone    0.000000        540.25      0.000000
Fashion Bazar     775.100000          0.00      0.000000
Super Bazar         0.000000          0.00    399.175000
Super Market        0.000000          0.00    374.936667

In [ ]:
# Fetch Average total cost per Location and store name
# Non-hierarchical data
pd.pivot_table(data = stores, index = 'StoreName', columns='Location', values = 'TotalCost', aggfunc = 'mean', fill_value=0)

Location          Chennai   Delhi  Kolkata  Mumbai
StoreName
Apparel Zone       501.36  378.95   474.89  365.59
Central Store        0.00  569.95  1129.88  380.40
Digital Bazar      655.40  253.18   469.39  927.15
Electronics Zone   395.20  450.00   558.20  757.60
Fashion Bazar      611.05  800.75  1200.90  487.70
Super Bazar        499.96  380.85   429.13  286.76
Super Market         0.00  360.20   456.41  308.20

In [68]:
# Fetch total stores per location and StoreType

pd.pivot_table(data = stores, index = 'StoreType', columns='Location', values = 'StoreCode', aggfunc = 'count', fill_value=0)

Location      Chennai  Delhi  Kolkata  Mumbai
StoreType
Apparel             3      3        3       3
Electronincs        2      2        2       2
Super Market        3      3        3       3

In [ ]:
# pd.crosstab - Will provide counts across 2 different columns

pd.crosstab(index=stores.StoreType, columns=stores.Location)

Location      Chennai  Delhi  Kolkata  Mumbai
StoreType
Apparel             3      3        3       3
Electronincs        2      2        2       2
Super Market        3      3        3       3

In [74]:
demog = pd.read_csv('Demographic_Data.csv')
trans = pd.read_csv('Transaction_Summary.csv')

In [75]:
demog

  CustName Gender  Age   Location  Salary Education      Mobile
0     Alex      M   21         UK   19159       PhD  8834777722
1      Tom      M   34        USA   10461         X  8812237772
2   Michel      M   25      India   19961       XII  8834777232
3  Michael      M   28    Belgium     821     B.Com  8831234222
4   Patrik      M   29  Australia   13743       MBA  8823427722
5     Hans      M   34      Japan   25000        MS  8834772342
6  Biliana      F   26     Russia    3000        MS  8837427722
7      Raj      M   29      India    2000        MS  9892877722
8    Laila      F   26      India    4000       MBA  7867277722
9  Prabhas      F   35      India   20000       MBA  8834772321

In [76]:
trans

,CustomerName,Total_Transaction_value,No_of_holding_prods,No_of_visits,No_of_channels
0,Alex,19159,3,3,1
1,Tom,10461,2,7,2
2,Michel,19961,4,8,3
3,Hans,821,1,2,2
4,Biliana,13743,6,9,3
5,Rajesh,25000,2,12,2
6,Laila,3000,1,6,1
7,Prabhas,2000,2,4,2
8,Ramu,30000,6,2,3

In [78]:
# Inner join

pd.merge(demog, trans, left_on= 'CustName', right_on='CustomerName', how = 'inner')

,CustName,Gender,Age,Location,Salary,Education,Mobile,CustomerName,Total_Transaction_value,No_of_holding_prods,No_of_visits,No_of_channels
0,Alex,M,21,UK,19159,PhD,8834777722,Alex,19159,3,3,1
1,Tom,M,34,USA,10461,X,8812237772,Tom,10461,2,7,2
2,Michel,M,25,India,19961,XII,8834777232,Michel,19961,4,8,3
3,Hans,M,34,Japan,25000,MS,8834772342,Hans,821,1,2,2
4,Biliana,F,26,Russia,3000,MS,8837427722,Biliana,13743,6,9,3
5,Laila,F,26,India,4000,MBA,7867277722,Laila,3000,1,6,1
6,Prabhas,F,35,India,20000,MBA,8834772321,Prabhas,2000,2,4,2

In [79]:
# left
pd.merge(demog, trans, left_on= 'CustName', right_on='CustomerName', how = 'left')

,CustName,Gender,Age,Location,Salary,Education,Mobile,CustomerName,Total_Transaction_value,No_of_holding_prods,No_of_visits,No_of_channels
0,Alex,M,21,UK,19159,PhD,8834777722,Alex,19159.0,3.0,3.0,1.0
1,Tom,M,34,USA,10461,X,8812237772,Tom,10461.0,2.0,7.0,2.0
2,Michel,M,25,India,19961,XII,8834777232,Michel,19961.0,4.0,8.0,3.0
3,Michael,M,28,Belgium,821,B.Com,8831234222,NaN,NaN,NaN,NaN,NaN
4,Patrik,M,29,Australia,13743,MBA,8823427722,NaN,NaN,NaN,NaN,NaN
5,Hans,M,34,Japan,25000,MS,8834772342,Hans,821.0,1.0,2.0,2.0
6,Biliana,F,26,Russia,3000,MS,8837427722,Biliana,13743.0,6.0,9.0,3.0
7,Raj,M,29,India,2000,MS,9892877722,NaN,NaN,NaN,NaN,NaN
8,Laila,F,26,India,4000,MBA,7867277722,Laila,3000.0,1.0,6.0,1.0
9,Prabhas,F,35,India,20000,MBA,8834772321,Prabhas,2000.0,2.0,4.0,2.0

In [80]:
# right
pd.merge(demog, trans, left_on= 'CustName', right_on='CustomerName', how = 'right')

,CustName,Gender,Age,Location,Salary,Education,Mobile,CustomerName,Total_Transaction_value,No_of_holding_prods,No_of_visits,No_of_channels
0,Alex,M,21.0,UK,19159.0,PhD,8.834778e+09,Alex,19159,3,3,1
1,Tom,M,34.0,USA,10461.0,X,8.812238e+09,Tom,10461,2,7,2
2,Michel,M,25.0,India,19961.0,XII,8.834777e+09,Michel,19961,4,8,3
3,Hans,M,34.0,Japan,25000.0,MS,8.834772e+09,Hans,821,1,2,2
4,Biliana,F,26.0,Russia,3000.0,MS,8.837428e+09,Biliana,13743,6,9,3
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rajesh,25000,2,12,2
6,Laila,F,26.0,India,4000.0,MBA,7.867278e+09,Laila,3000,1,6,1
7,Prabhas,F,35.0,India,20000.0,MBA,8.834772e+09,Prabhas,2000,2,4,2
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ramu,30000,6,2,3

In [ ]:
# outer
pd.merge(demog, trans, left_on= 'CustName', right_on='CustomerName', how = 'outer')

,CustName,Gender,Age,Location,Salary,Education,Mobile,CustomerName,Total_Transaction_value,No_of_holding_prods,No_of_visits,No_of_channels
0,Alex,M,21.0,UK,19159.0,PhD,8.834778e+09,Alex,19159.0,3.0,3.0,1.0
1,Biliana,F,26.0,Russia,3000.0,MS,8.837428e+09,Biliana,13743.0,6.0,9.0,3.0
2,Hans,M,34.0,Japan,25000.0,MS,8.834772e+09,Hans,821.0,1.0,2.0,2.0
3,Laila,F,26.0,India,4000.0,MBA,7.867278e+09,Laila,3000.0,1.0,6.0,1.0
4,Michael,M,28.0,Belgium,821.0,B.Com,8.831234e+09,NaN,NaN,NaN,NaN,NaN
5,Michel,M,25.0,India,19961.0,XII,8.834777e+09,Michel,19961.0,4.0,8.0,3.0
6,Patrik,M,29.0,Australia,13743.0,MBA,8.823428e+09,NaN,NaN,NaN,NaN,NaN
7,Prabhas,F,35.0,India,20000.0,MBA,8.834772e+09,Prabhas,2000.0,2.0,4.0,2.0
8,Raj,M,29.0,India,2000.0,MS,9.892878e+09,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rajesh,25000.0,2.0,12.0,2.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ramu,30000.0,6.0,2.0,3.0
11,Tom,M,34.0,USA,10461.0,X,8.812238e+09,Tom,10461.0,2.0,7.0,2.0

In [82]:
pd.merge?

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null value, those
    rows will be matched against each other. This is different from usual SQL
    join behaviour and can lead to unexpected results.

Parameters
----------
left : DataFrame or named Series
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.
on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default True
    If False, avoid copy if possible.

    .. note::
        The `copy` keyword will change behavior in pandas 3.0.
        `Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        will be enabled by default, which means that all methods with a
        `copy` keyword will use a lazy copy mechanism to defer the copy and
        ignore the `copy` keyword. The `copy` keyword will be removed in a
        future version of pandas.

        You can already get the future behavior and improvements through
        enabling copy on write ``pd.options.mode.copy_on_write = True``
indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Examples
--------
>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  bar        2  bar        6
3  baz        3  baz        7
4  foo        5  foo        5
5  foo        5  foo        8

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  bar           2  bar            6
3  baz           3  baz            7
4  foo           5  foo            5
5  foo           5  foo            8

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='object')

>>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
>>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
>>> df1
      a  b
0   foo  1
1   bar  2
>>> df2
      a  c
0   foo  3
1   baz  4

>>> df1.merge(df2, how='inner', on='a')
      a  b  c
0   foo  1  3

>>> df1.merge(df2, how='left', on='a')
      a  b  c
0   foo  1  3.0
1   bar  2  NaN

>>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
>>> df2 = pd.DataFrame({'right': [7, 8]})
>>> df1
    left
0   foo
1   bar
>>> df2
    right
0   7
1   8

>>> df1.merge(df2, how='cross')
   left  right
0   foo      7
1   foo      8
2   bar      7
3   bar      8
File:      c:\users\abhis\anaconda3\envs\turing\lib\site-packages\pandas\core\reshape\merge.py
Type:      function

In [83]:
# Explore suffixes argument in pd.merge

In [84]:
pd.merge(demog, trans, left_on= 'CustName', right_on='CustomerName', how = 'outer', indicator=True)

,CustName,Gender,Age,Location,Salary,Education,Mobile,CustomerName,Total_Transaction_value,No_of_holding_prods,No_of_visits,No_of_channels,_merge
0,Alex,M,21.0,UK,19159.0,PhD,8.834778e+09,Alex,19159.0,3.0,3.0,1.0,both
1,Biliana,F,26.0,Russia,3000.0,MS,8.837428e+09,Biliana,13743.0,6.0,9.0,3.0,both
2,Hans,M,34.0,Japan,25000.0,MS,8.834772e+09,Hans,821.0,1.0,2.0,2.0,both
3,Laila,F,26.0,India,4000.0,MBA,7.867278e+09,Laila,3000.0,1.0,6.0,1.0,both
4,Michael,M,28.0,Belgium,821.0,B.Com,8.831234e+09,NaN,NaN,NaN,NaN,NaN,left_only
5,Michel,M,25.0,India,19961.0,XII,8.834777e+09,Michel,19961.0,4.0,8.0,3.0,both
6,Patrik,M,29.0,Australia,13743.0,MBA,8.823428e+09,NaN,NaN,NaN,NaN,NaN,left_only
7,Prabhas,F,35.0,India,20000.0,MBA,8.834772e+09,Prabhas,2000.0,2.0,4.0,2.0,both
8,Raj,M,29.0,India,2000.0,MS,9.892878e+09,NaN,NaN,NaN,NaN,NaN,left_only
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rajesh,25000.0,2.0,12.0,2.0,right_only
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ramu,30000.0,6.0,2.0,3.0,right_only
11,Tom,M,34.0,USA,10461.0,X,8.812238e+09,Tom,10461.0,2.0,7.0,2.0,both

In [87]:
# Identify the customers who never did any transactions

# left
temp = pd.merge(demog, trans, left_on= 'CustName', right_on='CustomerName', how = 'left', indicator=True)
temp[temp._merge == 'left_only']

,CustName,Gender,Age,Location,Salary,Education,Mobile,CustomerName,Total_Transaction_value,No_of_holding_prods,No_of_visits,No_of_channels,_merge
3,Michael,M,28,Belgium,821,B.Com,8831234222,NaN,NaN,NaN,NaN,NaN,left_only
4,Patrik,M,29,Australia,13743,MBA,8823427722,NaN,NaN,NaN,NaN,NaN,left_only
7,Raj,M,29,India,2000,MS,9892877722,NaN,NaN,NaN,NaN,NaN,left_only

In [90]:
# What's the overall transactional value by each location?
# For location where we don't have customers, just put 0

temp = pd.merge(demog, trans, left_on= 'CustName', right_on='CustomerName', how = 'left')
temp.groupby('Location').Total_Transaction_value.sum()

Location
Australia        0.0
Belgium          0.0
India        24961.0
Japan          821.0
Russia       13743.0
UK           19159.0
USA          10461.0
Name: Total_Transaction_value, dtype: float64

In [93]:
# Define average transactional value by location and Education in form of cross table.

pd.pivot_table(data = pd.merge(demog, trans, left_on= 'CustName', right_on='CustomerName', how = 'inner'),
                index = 'Location', columns = 'Education', aggfunc='mean', values = 'Total_Transaction_value', fill_value=0          
)

Education     MBA       MS      PhD        X      XII
Location
India      2500.0      0.0      0.0      0.0  19961.0
Japan         0.0    821.0      0.0      0.0      0.0
Russia        0.0  13743.0      0.0      0.0      0.0
UK            0.0      0.0  19159.0      0.0      0.0
USA           0.0      0.0      0.0  10461.0      0.0

In [4]:
# pd.concat -> Explore this function
import pandas as pd
import numpy as np

lst_df = []
for i in range(4):
    lst_df.append(pd.read_csv(f'POS_Q{i+1}.csv'))

lst_df[3]

,Date,Configuration,Customer Postcode,Store Postcode,Retail Price,month
0,10-01-13 0:02,579,EC1V 2QH,SW1P 3AU,510,10
1,10-01-13 0:05,523,E3 4QS,E2 0RY,550,10
2,10-01-13 0:07,574,EC1M 5NA,NW5 2QH,660,10
3,10-01-13 0:08,62,N7 6PN,N17 6QA,320,10
4,10-01-13 0:11,295,EC1N 8QS,SW1P 3AU,545,10
5,10-01-13 0:11,100,SE1 1NA,SE1 2BN,510,10
6,10-01-13 0:11,475,EC1V 9NU,SW1P 3AU,520,10

In [5]:
lst_df[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               5 non-null      object
 1   Configuration      5 non-null      int64
 2   Customer Postcode  5 non-null      object
 3   Store Postcode     5 non-null      object
 4   Retail Price       5 non-null      int64
 5   month              5 non-null      int64
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes

In [6]:
lst_df[1].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10 non-null     object
 1   Configuration      10 non-null     int64
 2   Customer Postcode  10 non-null     object
 3   Store Postcode     10 non-null     object
 4   Retail Price       10 non-null     int64
 5   month              10 non-null     int64
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [7]:
lst_df[2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               15 non-null     object
 1   Configuration      15 non-null     int64
 2   Customer Postcode  15 non-null     object
 3   Store Postcode     15 non-null     object
 4   Retail Price       15 non-null     int64
 5   month              15 non-null     int64
dtypes: int64(3), object(3)
memory usage: 852.0+ bytes

In [8]:
lst_df[3].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               7 non-null      object
 1   Configuration      7 non-null      int64
 2   Customer Postcode  7 non-null      object
 3   Store Postcode     7 non-null      object
 4   Retail Price       7 non-null      int64
 5   month              7 non-null      int64
dtypes: int64(3), object(3)
memory usage: 468.0+ bytes

In [ ]:
pd.concat(lst_df) # Vertical stacking
# Explore axis argument to convert the pd.concat to a horizontal stacking

,Date,Configuration,Customer Postcode,Store Postcode,Retail Price,month
0,01-01-13 0:01,163,EC4V 5BH,SE1 2BN,455,1
1,01-01-13 0:02,320,SW4 0JL,SW12 9HD,545,1
2,01-01-13 0:04,23,EC3V 1LR,E2 0RY,515,1
3,01-01-13 0:04,169,SW1P 3AU,SE1 2BN,395,1
4,01-01-13 0:06,365,EC4V 4EG,SW1V 4QQ,585,1
0,04-01-13 0:00,216,KT2 7PX,W4 3PH,505,4
1,04-01-13 0:05,317,EC3N 2AE,SW1P 3AU,520,4
2,04-01-13 0:32,176,W1T 1HH,NW5 2QH,450,4
3,04-01-13 0:43,176,SE3 0QJ,SE8 3JD,450,4
4,04-01-13 0:47,61,W1W 6DL,SW1V 4QQ,430,4
5,04-01-13 0:48,163,NW1 4BX,SW1P 3AU,440,4
6,04-01-13 0:56,302,E14 0BB,SE1 2BN,445,4
7,04-01-13 0:58,21,SE1 8SW,SW1V 4QQ,440,4
8,04-01-13 1:00,73,W1U 5JN,SW1P 3AU,395,4
9,04-01-13 1:03,317,W8 7SR,W10 6HQ,520,4
0,07-01-13 0:00,23,E4 9PB,E7 8NW,485,7
1,07-01-13 0:06,55,WC2A 2HF,SW1V 4QQ,480,7
2,07-01-13 0:10,222,W1K 6JG,W10 6HQ,395,7
3,07-01-13 0:11,595,EC3M 7HR,SE1 2BN,555,7
4,07-01-13 0:13,8,W1H 5HT,SW1V 4QQ,410,7
5,07-01-13 0:13,323,SE1 2PF,SE1 2BN,560,7
6,07-01-13 0:13,628,KT2 5EB,KT2 5AU,530,7
7,07-01-13 0:14,465,SW1H 9LA,SE1 2BN,520,7
8,07-01-13 0:14,177,SW7 4SS,W10 6HQ,440,7
9,07-01-13 0:14,369,EC1R 1UY,SE1 2BN,570,7
10,07-01-13 0:15,607,SE24 0NG,SW1P 3AU,615,7
11,07-01-13 0:15,606,N7 9BL,E2 0RY,505,7
12,07-01-13 0:17,532,W1W 5QU,SW1V 4QQ,610,7
13,07-01-13 0:19,316,SE1 9AA,SE1 2BN,435,7
14,07-01-13 0:19,386,SE16 4QZ,SE8 3JD,570,7
0,10-01-13 0:02,579,EC1V 2QH,SW1P 3AU,510,10
1,10-01-13 0:05,523,E3 4QS,E2 0RY,550,10
2,10-01-13 0:07,574,EC1M 5NA,NW5 2QH,660,10
3,10-01-13 0:08,62,N7 6PN,N17 6QA,320,10
4,10-01-13 0:11,295,EC1N 8QS,SW1P 3AU,545,10
5,10-01-13 0:11,100,SE1 1NA,SE1 2BN,510,10
6,10-01-13 0:11,475,EC1V 9NU,SW1P 3AU,520,10