### Database Connection

In [17]:
# Defining libraries and credentials
import pyodbc # We can also use SQLAlchemy to define the connections strings.
import pandas as pd

server_name = 'localhost\\SQLEXPRESS'  # e.g., 'localhost\SQLEXPRESS' or 'your_server_ip'
database_name = 'AdventureWorksDW2020'

# Define username and password in case you are connecting with SQL SERVER apart from your own machine
connection_string = (
        f'DRIVER={{ODBC Driver 17 for SQL Server}};'  # Adjust driver name if needed
        f'SERVER={server_name};'
        f'DATABASE={database_name};'
        f'Trusted_Connection=yes;')

In [18]:
try:
    cnxn = pyodbc.connect(connection_string)
    print("Connection established successfully!")
except pyodbc.Error as ex:
    sqlstate = ex.args[0]
    print(f"Error connecting to SQL Server: {sqlstate}")
    exit()

Connection established successfully!

In [19]:
query = "SELECT * FROM DimProduct;"  # Replace with your SQL query
df = pd.read_sql(query, cnxn)

df.head()

C:\Users\abhis\AppData\Local\Temp\ipykernel_22144\2131755205.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, cnxn)

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,None,None,Adjustable Race,,,NaN,False,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
1,2,BA-8327,NaN,None,None,Bearing Ball,,,NaN,False,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
2,3,BE-2349,NaN,None,None,BB Ball Bearing,,,NaN,False,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
3,4,BE-2908,NaN,None,None,Headset Ball Bearings,,,NaN,False,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current
4,5,BL-2036,NaN,None,None,Blade,,,NaN,False,...,None,None,None,None,None,None,None,2003-07-01,NaT,Current

In [16]:
cnxn.close()
print("Connection closed.")

Connection closed.

In [21]:
import numpy as np

stores = pd.read_csv('stores.csv')

stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2

In [46]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StoreCode        32 non-null     object
 1   StoreName        32 non-null     object
 2   StoreType        32 non-null     object
 3   Location         32 non-null     object
 4   OperatingCost    32 non-null     float64
 5   Staff_Cnt        32 non-null     int64
 6   TotalSales       32 non-null     float64
 7   Total_Customers  32 non-null     int64
 8   AcqCostPercust   29 non-null     float64
 9   BasketSize       32 non-null     float64
 10  ProfitPercust    32 non-null     float64
 11  OwnStore         32 non-null     int64
 12  OnlinePresence   32 non-null     int64
 13  Tenure           32 non-null     int64
 14  StoreSegment     32 non-null     int64
dtypes: float64(5), int64(6), object(4)
memory usage: 3.9+ KB

In [ ]:
# Subsetting the data (Get a subset of the data) - Columns

stores.columns

Index(['StoreCode', 'StoreName', 'StoreType', 'Location', 'OperatingCost',
       'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment'],
      dtype='object')

In [37]:
stores2 = stores[['OperatingCost', 'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment']] # Chaining of operation - Subsetting + sampling

In [ ]:
stores2.loc[1:5, ['OperatingCost','TotalSales', 'Total_Customers']] # Targeting user defined indexes

   OperatingCost  TotalSales  Total_Customers
1           21.0       160.0              110
2           22.8       108.0               93
3           21.4       258.0              110
4           18.7       360.0              175
5           18.1       225.0              105

In [44]:
# select_dtypes

stores_num = stores.select_dtypes(['int', 'float'])
stores_obj = stores.select_dtypes('object')

In [45]:
stores_obj.head()

  StoreCode         StoreName     StoreType Location
0    STR101  Electronics Zone  Electronincs    Delhi
1    STR102      Apparel Zone       Apparel    Delhi
2    STR103       Super Bazar  Super Market    Delhi
3    STR104      Super Market  Super Market    Delhi
4    STR105     Central Store  Super Market    Delhi

In [53]:
# Deriving calculated columns (creating new columns)

# Get the sales values after applying 5% of the discount on the products

stores['Discounted Sales'] = stores.TotalSales - stores.TotalSales * 0.05 # Broadcasting + vectorization are allowed

In [54]:
stores.columns

Index(['StoreCode', 'StoreName', 'StoreType', 'Location', 'OperatingCost',
       'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment', 'Discounted Sales'],
      dtype='object')

In [57]:
stores['Discounted Sales'].head()

0    152.0
1    152.0
2    102.6
3    245.1
4    342.0
Name: Discounted Sales, dtype: float64

In [58]:
# Total Cost = Operating Cost +  Total Customer * AcqCostPercust

stores['TotalCost'] = stores.OperatingCost + stores.Total_Customers * stores.AcqCostPercust

stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95

In [ ]:
# .assign() - Define multiple columns at the same time
# .insert()

# *args - accept the tuple in the function - 1,2,3,4,5 => (1,2,3,4,5)
# **kwargs - accept the dictionary in the function - a = 1, b = 2 => {'a': 1, 'b': 2}

stores = stores.assign(TotalCost2 = stores.OperatingCost + stores.Total_Customers * stores.AcqCostPercust, 
                    RandomInfo = 10)
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost,TotalCost2,RandomInfo
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00,450.00,10
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00,450.00,10
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85,380.85,10
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20,360.20,10
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95,569.95,10

In [ ]:
stores.insert(1, 'TotalCost3', stores.OperatingCost + stores.Total_Customers * stores.AcqCostPercust) # in memory operation - expensive operation

In [64]:
stores.head()

,StoreCode,TotalCost3,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost,TotalCost2,RandomInfo
0,STR101,450.00,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00,450.00,10
1,STR102,450.00,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00,450.00,10
2,STR103,380.85,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85,380.85,10
3,STR104,360.20,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20,360.20,10
4,STR105,569.95,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95,569.95,10

In [67]:
# Dropping the variables

stores.drop(columns=['TotalCost2', 'RandomInfo', 'TotalCost3'], inplace=True)
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95

In [74]:
# Filtering of dataframe
# Fetch the stores located in Chennai

stores[stores.Location == 'Chennai']

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.150,22.90,1,0,4,2,133.76,395.20
9,STR110,Apparel Zone,Apparel,Chennai,19.2,60,167.6,123,3.92,3.440,18.30,1,0,4,4,159.22,501.36
10,STR111,Super Bazar,Super Market,Chennai,17.8,60,167.6,123,3.92,3.440,18.90,1,0,4,4,159.22,499.96
11,STR112,Super Market,Super Market,Chennai,16.4,80,275.8,180,NaN,4.070,17.40,0,0,3,3,262.01,NaN
12,STR113,Central Store,Super Market,Chennai,17.3,80,275.8,180,NaN,3.730,17.60,0,0,3,3,262.01,NaN
13,STR114,Apparel Zone,Apparel,Chennai,15.2,80,275.8,180,NaN,3.780,18.00,0,0,3,3,262.01,NaN
14,STR115,Fashion Bazar,Apparel,Chennai,10.4,80,472.0,205,2.93,5.250,17.98,0,0,3,4,448.40,611.05
15,STR116,Digital Bazar,Electronincs,Chennai,10.4,80,460.0,215,3.00,5.424,17.82,0,0,3,4,437.00,655.40

In [78]:
# Fetch the stores located in Chennai or Delhi

stores[(stores.Location == 'Chennai') | (stores.Location == 'Delhi')]

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.000,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.000,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.600,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.100,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.000,569.95
5,STR106,Apparel Zone,Apparel,Delhi,18.1,60,225.0,105,2.76,3.460,20.22,1,0,3,1,213.750,307.90
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.570,15.84,0,0,3,4,342.000,800.75
7,STR108,Digital Bazar,Electronincs,Delhi,24.4,40,146.7,62,3.69,3.190,20.00,1,0,4,2,139.365,253.18
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.150,22.90,1,0,4,2,133.760,395.20
9,STR110,Apparel Zone,Apparel,Chennai,19.2,60,167.6,123,3.92,3.440,18.30,1,0,4,4,159.220,501.36
10,STR111,Super Bazar,Super Market,Chennai,17.8,60,167.6,123,3.92,3.440,18.90,1,0,4,4,159.220,499.96
11,STR112,Super Market,Super Market,Chennai,16.4,80,275.8,180,NaN,4.070,17.40,0,0,3,3,262.010,NaN
12,STR113,Central Store,Super Market,Chennai,17.3,80,275.8,180,NaN,3.730,17.60,0,0,3,3,262.010,NaN
13,STR114,Apparel Zone,Apparel,Chennai,15.2,80,275.8,180,NaN,3.780,18.00,0,0,3,3,262.010,NaN
14,STR115,Fashion Bazar,Apparel,Chennai,10.4,80,472.0,205,2.93,5.250,17.98,0,0,3,4,448.400,611.05
15,STR116,Digital Bazar,Electronincs,Chennai,10.4,80,460.0,215,3.00,5.424,17.82,0,0,3,4,437.000,655.40

In [79]:
stores[stores.Location.isin(['Chennai','Delhi'])]

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.000,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.000,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.600,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.100,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.000,569.95
5,STR106,Apparel Zone,Apparel,Delhi,18.1,60,225.0,105,2.76,3.460,20.22,1,0,3,1,213.750,307.90
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.570,15.84,0,0,3,4,342.000,800.75
7,STR108,Digital Bazar,Electronincs,Delhi,24.4,40,146.7,62,3.69,3.190,20.00,1,0,4,2,139.365,253.18
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.150,22.90,1,0,4,2,133.760,395.20
9,STR110,Apparel Zone,Apparel,Chennai,19.2,60,167.6,123,3.92,3.440,18.30,1,0,4,4,159.220,501.36
10,STR111,Super Bazar,Super Market,Chennai,17.8,60,167.6,123,3.92,3.440,18.90,1,0,4,4,159.220,499.96
11,STR112,Super Market,Super Market,Chennai,16.4,80,275.8,180,NaN,4.070,17.40,0,0,3,3,262.010,NaN
12,STR113,Central Store,Super Market,Chennai,17.3,80,275.8,180,NaN,3.730,17.60,0,0,3,3,262.010,NaN
13,STR114,Apparel Zone,Apparel,Chennai,15.2,80,275.8,180,NaN,3.780,18.00,0,0,3,3,262.010,NaN
14,STR115,Fashion Bazar,Apparel,Chennai,10.4,80,472.0,205,2.93,5.250,17.98,0,0,3,4,448.400,611.05
15,STR116,Digital Bazar,Electronincs,Chennai,10.4,80,460.0,215,3.00,5.424,17.82,0,0,3,4,437.000,655.40

In [ ]:
# Fetch the Total Sales and Customers in stores located in Chennai or Delhi 
stores.loc[stores.Location.isin(['Chennai','Delhi']), ['TotalSales', 'Total_Customers']] # Filtering + Subsetting - 1 single operation
# stores[stores.Location.isin(['Chennai','Delhi'])][['TotalSales', 'Total_Customers']] # 2 different operations

    TotalSales  Total_Customers
0        160.0              110
1        160.0              110
2        108.0               93
3        258.0              110
4        360.0              175
5        225.0              105
6        360.0              245
7        146.7               62
8        140.8               95
9        167.6              123
10       167.6              123
11       275.8              180
12       275.8              180
13       275.8              180
14       472.0              205
15       460.0              215

In [84]:
# Explore time library to measure performance

In [86]:
# Find out the stores having Total Cost higher than average total cost
# average total cost = 100
# Total Cost > 100

stores[stores.TotalCost > stores.TotalCost.mean()]

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.00,569.95
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.570,15.84,0,0,3,4,342.00,800.75
14,STR115,Fashion Bazar,Apparel,Chennai,10.4,80,472.0,205,2.93,5.250,17.98,0,0,3,4,448.40,611.05
15,STR116,Digital Bazar,Electronincs,Chennai,10.4,80,460.0,215,3.00,5.424,17.82,0,0,3,4,437.00,655.40
16,STR117,Electronics Zone,Electronincs,Mumbai,14.7,80,440.0,230,3.23,5.345,17.42,0,0,3,4,418.00,757.60
23,STR124,Digital Bazar,Electronincs,Mumbai,13.3,80,350.0,245,3.73,3.840,15.41,0,0,3,4,332.50,927.15
24,STR125,Electronics Zone,Electronincs,Kolkata,19.2,80,400.0,175,3.08,3.845,17.05,0,0,3,2,380.00,558.20
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.170,14.50,0,1,5,4,333.45,1129.88
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.770,15.50,0,1,5,4,137.75,653.20
30,STR131,Fashion Bazar,Apparel,Kolkata,15.0,80,301.0,335,3.54,3.570,14.60,0,1,5,4,285.95,1200.90

In [87]:
stores.TotalCost.mean()

np.float64(527.8786206896551)

In [ ]:
# Identify the total stores in Delhi which are Super Market
# Identify the total sales in Delhi

In [ ]:
# Renaming the columns
stores.rename(columns={'Total_Customers': 'TotalCustomers', 'Staff_Cnt': 'StaffCnt'}, inplace=True)
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,StaffCnt,TotalSales,TotalCustomers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,Discounted Sales,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,152.0,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,152.0,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,102.6,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,245.1,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,342.0,569.95

In [ ]:
stores['DiscountedSales'] = stores['Discounted Sales'] # information is repeated in another colunns

In [91]:
stores.to_csv('stores_new.csv', index=False)